* Отчёт
- [[https://www.kaggle.com/malahai/kernelc27cd561ec?scriptVersionId=36705252][Кернел]] на kaggle с обучением модели. Модель на гитхабе не получилось сохранить из-за размера - 400 мб. Ее можно скачать из поля output в кернеле
- [[http://malahai.pythonanywhere.com/comment/][Сайт]] на pythonanywhere.com
- [[https://github.com/gazon1/GreenAtom][Код]] django проекта на гитхабе 
** Архитектура приложения
Проект на django состоит из одного приложения "comment_sentiment". Его задача - принять по пути "comment/" отзыв на фильм на английском,
передать отзыв уже обученной модели и вывести:
- Класс отзыва: Positive или Negative
- Оценку фильму по комментарию - число от 0 до 10.
  
Как выставляется оценка фильма: на выходе нейросети получаем предсказание в виде вероятности отнесения отзыва к positive классу.
Эту вероятность разделяем на 10 равных отрезков. Отрезки идут друг за другом и не пересекаются. Затем отрезки нумеруются от 0 до 10 и потом,
в зависимости от попадания предсказания в один из этих отрезков выводится номер этого отрезка. Это и есть оценка фильму.
Этот алгоритм записан в функции [[https://github.com/gazon1/GreenAtom/blob/master/comment_sentiment/model.py#L88][return_pos_neg_and_rating]]

Оценка и класс отзыва по тексту отзыва возвращаются функцией [[https://github.com/gazon1/GreenAtom/blob/master/comment_sentiment/model.py#L99][predict_sentiment]]

В интерфейсе поле для ввода отзыва на фильм и кнопка "send". 

** Архитектура модели и схема решения
Полный пайплайн обучения и архитектура модели написана в [[https://www.kaggle.com/malahai/kernelc27cd561ec?scriptVersionId=36705252][кернеле]] на kaggle

1. Текст отызва токенизируется, обрезается по 512 символам, добавляется токен начала и конца. См функцию [[https://github.com/gazon1/GreenAtom/blob/master/comment_sentiment/model.py#L99][predict_sentiment]]
2. Список токенов проходит через предобученную модель Bert из библиотеки transformers
3. Выход Bert пропускаем через GRU c двумя слоями и размерностью векторов скрытого состояния 256. Dropout 0.25
4. В конце линейный слой сжимает тензор до размерности [batch size, 1] - это логиты
5. Вероятность отнесения отзыва к положительному классу = sigmoid(logit)
   
На Валидации эта модель показывает accuracy в 0.89
